### ISSUE TITLE
Need to show when company id update In document

### ISSUE THREAD

**Issue by KoukiHama** [eclipse-sw360/sw360.website#41]
Sometime, we need to chgange this, but it is hard to know when it is required.  

need to add this kinds of comment

* Please set `sw360.liferay.company.id = 20099` in config file `sw360.properties`

@tuannn2  do you have idea?

Recently we deleted this comment on the Version 16 to 17 update docment. 

Is it OK for the process?

https://github.com/eclipse-sw360/sw360.website/commit/75dc9a59da3ca6f4093a50b7ca6fb265c98fb823#r119417937

**Comment by ag4ums** [comment]
@KoukiHama @tuannn2, you need this so that the company id from users_ table is not different from the previous company id in liferay database. and also to setup the Oauth with the liferay version upgrade.

**Comment by tuannn2** [comment]
@KoukiHama, @ag4ums 

We can have skip change company id when from 16 to 17 because we have done upgrade liferay from 7.3 to 7.4.
The change company.id =20099 is necessary when we do the installation from scratch sw360 in version 17.

**Comment by KoukiHama** [comment]
@ag4ums 

Did you use upgrade program when you update liferay from 7.3 to 7.4?

**Comment by ag4ums** [comment]
steps looks good, mentioned here as well, https://github.com/eclipse-sw360/sw360/pull/916#issuecomment-667818520
after upgrade reindexing not sure, as reindexing will be tiggered automatically as you use search interface.
